// Departamentos de Uruguay con sus ciudades/zonas principales.
// Los selects se generan desde acá; el matching en la DB es por texto igual.

export const DEPARTAMENTOS = [
  'Artigas',
  'Canelones',
  'Cerro Largo',
  'Colonia',
  'Durazno',
  'Flores',
  'Florida',
  'Lavalleja',
  'Maldonado',
  'Montevideo',
  'Paysandú',
  'Río Negro',
  'Rivera',
  'Rocha',
  'Salto',
  'San José',
  'Soriano',
  'Tacuarembó',
  'Treinta y Tres',
] as const

export const CIUDADES_POR_DEPARTAMENTO: Record<string, string[]> = {
  Artigas: ['Artigas', 'Bella Unión', 'Tomás Gomensoro', 'Baltasar Brum'],
  Canelones: [
    'Ciudad de la Costa',
    'Las Piedras',
    'Pando',
    'Canelones',
    'Santa Lucía',
    'Salinas',
    'Atlántida',
    'La Paz',
    'Progreso',
    'San Ramón',
  ],
  'Cerro Largo': ['Melo', 'Río Branco', 'Fraile Muerto', 'Isidoro Noblía'],
  Colonia: ['Colonia del Sacramento', 'Carmelo', 'Juan Lacaze', 'Nueva Helvecia', 'Rosario'],
  Durazno: ['Durazno', 'Sarandí del Yí', 'Villa del Carmen'],
  Flores: ['Trinidad', 'Ismael Cortinas'],
  Florida: ['Florida', 'Sarandí Grande', 'Casupá', 'Fray Marcos'],
  Lavalleja: ['Minas', 'José Pedro Varela', 'Solís de Mataojo'],
  Maldonado: ['Maldonado', 'Punta del Este', 'San Carlos', 'Piriápolis', 'Pan de Azúcar'],
  Montevideo: [
    'Montevideo',
    'Centro',
    'Ciudad Vieja',
    'Pocitos',
    'Carrasco',
    'Malvín',
    'Buceo',
    'Sayago',
    'Colón',
    'Cerro',
  ],
  Paysandú: ['Paysandú', 'Guichón', 'Quebracho', 'Tambores'],
  'Río Negro': ['Fray Bentos', 'Young', 'Nuevo Berlín'],
  Rivera: ['Rivera', 'Tranqueras', 'Vichadero', 'Minas de Corrales'],
  Rocha: ['Rocha', 'Chuy', 'Castillos', 'La Paloma', 'Lascano'],
  Salto: ['Salto', 'Constitución', 'Belén', 'Chacras de Belén'],
  'San José': ['San José de Mayo', 'Ciudad del Plata', 'Libertad', 'Rodríguez'],
  Soriano: ['Mercedes', 'Dolores', 'Cardona', 'Palmitas'],
  Tacuarembó: ['Tacuarembó', 'Paso de los Toros', 'San Gregorio de Polanco'],
  'Treinta y Tres': ['Treinta y Tres', 'Vergara', 'Cerro Chato'],
}

export const DEPARTAMENTO_DEFAULT = 'Salto'
